import 'bootstrap/dist/css/bootstrap.css';
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Providers from './providers'
import BootstrapClient from '@/components/BootstrapClient';
import MenuBar from '@/components/layout/MenuBar';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

import { useSession } from "next-auth/react"
import LoginScreen from '@/components/Auth/LoginScreen';
import AuthLayout from '@/components/layout/AuthLayout';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    
    <html lang="en">
      <body className={inter.className}>
    
      <Providers>
        <AuthLayout title='MG'>
        {children}
        </AuthLayout>
        </Providers>
               
      
      <BootstrapClient />
        </body>
    </html>
  )
}
